version: '3'
services:
    db:
        image: postgres
        environment:
            POSTGRES_PASSWORD: abc123
            POSTGRES_USER: postgres
            POSTGRES_DB: test-db
        volumes:
            - ./pgdata:/var/lib/postgresql/data
        ports:
            - '5432:5432'
    app:
        container_name: node-app
        depends_on: 
            - db
        command: ["./wait-for-it.sh", "db:5432", "--", "npm", "start"]
        restart: always
        build: .
        ports:
            - '9001:3000'
        volumes:
            - .:/app
        